/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as DashboardTransportistaRouteImport } from './routes/dashboard.transportista'
import { Route as DashboardCompradorRouteImport } from './routes/dashboard.comprador'
import { Route as DashboardAgricultorRouteImport } from './routes/dashboard.agricultor'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransportistaRoute = DashboardTransportistaRouteImport.update({
  id: '/dashboard/transportista',
  path: '/dashboard/transportista',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompradorRoute = DashboardCompradorRouteImport.update({
  id: '/dashboard/comprador',
  path: '/dashboard/comprador',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgricultorRoute = DashboardAgricultorRouteImport.update({
  id: '/dashboard/agricultor',
  path: '/dashboard/agricultor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/productos': typeof ProductosRoute
  '/registro': typeof RegistroRoute
  '/dashboard/agricultor': typeof DashboardAgricultorRoute
  '/dashboard/comprador': typeof DashboardCompradorRoute
  '/dashboard/transportista': typeof DashboardTransportistaRoute
  '/producto/$id': typeof ProductoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/productos': typeof ProductosRoute
  '/registro': typeof RegistroRoute
  '/dashboard/agricultor': typeof DashboardAgricultorRoute
  '/dashboard/comprador': typeof DashboardCompradorRoute
  '/dashboard/transportista': typeof DashboardTransportistaRoute
  '/producto/$id': typeof ProductoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/productos': typeof ProductosRoute
  '/registro': typeof RegistroRoute
  '/dashboard/agricultor': typeof DashboardAgricultorRoute
  '/dashboard/comprador': typeof DashboardCompradorRoute
  '/dashboard/transportista': typeof DashboardTransportistaRoute
  '/producto/$id': typeof ProductoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/productos'
    | '/registro'
    | '/dashboard/agricultor'
    | '/dashboard/comprador'
    | '/dashboard/transportista'
    | '/producto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/productos'
    | '/registro'
    | '/dashboard/agricultor'
    | '/dashboard/comprador'
    | '/dashboard/transportista'
    | '/producto/$id'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/productos'
    | '/registro'
    | '/dashboard/agricultor'
    | '/dashboard/comprador'
    | '/dashboard/transportista'
    | '/producto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ProductosRoute: typeof ProductosRoute
  RegistroRoute: typeof RegistroRoute
  DashboardAgricultorRoute: typeof DashboardAgricultorRoute
  DashboardCompradorRoute: typeof DashboardCompradorRoute
  DashboardTransportistaRoute: typeof DashboardTransportistaRoute
  ProductoIdRoute: typeof ProductoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transportista': {
      id: '/dashboard/transportista'
      path: '/dashboard/transportista'
      fullPath: '/dashboard/transportista'
      preLoaderRoute: typeof DashboardTransportistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/comprador': {
      id: '/dashboard/comprador'
      path: '/dashboard/comprador'
      fullPath: '/dashboard/comprador'
      preLoaderRoute: typeof DashboardCompradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agricultor': {
      id: '/dashboard/agricultor'
      path: '/dashboard/agricultor'
      fullPath: '/dashboard/agricultor'
      preLoaderRoute: typeof DashboardAgricultorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ProductosRoute: ProductosRoute,
  RegistroRoute: RegistroRoute,
  DashboardAgricultorRoute: DashboardAgricultorRoute,
  DashboardCompradorRoute: DashboardCompradorRoute,
  DashboardTransportistaRoute: DashboardTransportistaRoute,
  ProductoIdRoute: ProductoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
